apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - name: reservations
          image: d2mittal/reservations
          env:
            - name: MONGO_URI
              value: "mongodb://reservations-mongo-srv:27017/reservations"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: facility-reservation
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 
---
apiVersion: v1
kind: Service
metadata:
  name: reservations-srv
spec:
  selector:
    app: reservations
  ports:
    - name: reservations
      protocol: TCP
      port: 3000
      targetPort: 3000